name: Suggestion
description: Suggest a cheat or script
title: "IDEA: Script idea name"
labels: ["enhancement"]
body:
  - type: input
    id: gamemode
    attributes:
      label: Gamemode
      description: Gamemode for cheat to be for
      placeholder: Gamemode
  - type: textarea
    id: function
    attributes:
      label: Function
      description: What does the script do?
      placeholder: Script function
    validations:
      required: true
  - type: dropdown
    id: confirm
    attributes:
      label: FaQ
      description: Please make sure to read [the FaQ](https://github.com/Minesraft2/Blooket-Cheats/wiki#faq) before submitting any suggestions
      multiple: true
      options:
        - I have not read the FaQ and my suggestion may be impossible
        - I have read the FaQ and doesn't specify if my suggestion is possible
    validations:
      required: true
   - type: dropdown
    id: confirm
    attributes:
      label: Previous Suggestions
      description: Please make sure to look at previous issues to check if your suggestion has already been looked at before submitting any suggestions
      multiple: true
      options:
        - I have not looked at previous issues and someone may have asked for my suggestion
        - I have looked at previous issues and my suggestion has not already been asked for
    validations:
      required: true
